In [53]:
import re

In [54]:
text = "Hi boss how are you"
if re.search('boss',text):
    print("Respect")
else:
    print("not boss")

Respect


In [55]:
text = "any one can do any thing if he thing any to one"
re.split('any', text)

['', ' one can do ', ' thing if he thing ', ' to one']

In [56]:
re.findall('any',text)

['any', 'any', 'any']

In [57]:
grade = 'AAABBABACABACB'
re.findall("AB", grade)

['AB', 'AB', 'AB']

In [58]:
re.findall("[AB]",grade)

['A', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'A', 'B']

In [59]:
re.findall("[A][BC]",grade)# A Followed by B or C

['AB', 'AB', 'AC', 'AB', 'AC']

In [60]:
re.findall("AB|AC",grade)

['AB', 'AB', 'AC', 'AB', 'AC']

In [61]:
re.findall("[^A]",grade) # Start with A

['B', 'B', 'B', 'C', 'B', 'C', 'B']

# Quentifier

In [62]:
grade = 'AAAAAABBCABAACABAACB'
re.findall("A{1,}",grade)

['AAAAAA', 'A', 'AA', 'A', 'AA']

In [63]:
re.findall("A{1,1}A{1,1}",grade)

['AA', 'AA', 'AA', 'AA', 'AA']

In [64]:
re.findall("A{2,2}", grade)

['AA', 'AA', 'AA', 'AA', 'AA']

In [65]:
re.findall("AA", grade)

['AA', 'AA', 'AA', 'AA', 'AA']

In [66]:
re.findall("A{1,}B{1,}C{1,}", grade)

['AAAAAABBC']

In [67]:
with open("ferpa.txt", 'r') as file:
    wiki = file.read()
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [68]:
re.findall("[a-zA-z]{1,100}\[edit\]", wiki)#any uppercase or lower case followed by edit

['Overview[edit]', 'records[edit]', 'records[edit]']

In [69]:
re.findall("[\w]{1,100}\[edit\]", wiki)# \w mean any word or number

['Overview[edit]', 'records[edit]', 'records[edit]']

In [70]:
re.findall("[\w]*\[edit\]", wiki)# * = o or more

['Overview[edit]', 'records[edit]', 'records[edit]']

In [71]:
re.findall("[\w ]*\[edit\]", wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [72]:
for item in re.findall("[\w ]*\[edit\]", wiki):
    print(item.split("[")[0])

Overview
Access to public records
Student medical records


# Group

In [74]:
re.findall("[\w ]*\[edit\]", wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [78]:
for item in re.finditer("([\w ]*)(\[edit\])",wiki):
    print(item.groups())

('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')


In [85]:
for item in re.finditer("([\w ]*)(\[edit\])",wiki):
    print(item.group(1))

Overview
Access to public records
Student medical records


# Look-ahead Look-behind

In [86]:
# One more concept to be familiar with is called "look ahead" and "look behind" matching. In this case, the
# pattern being given to the regex engine is for text either before or after the text we are trying to
# isolate. For example, in our headers we want to isolate text which  comes before the [edit] rendering, but
# we actually don't care about the [edit] text itself. Thus far we have been throwing the [edit] away, but if
# we want to use them to match but don't want to capture them we could put them in a group and use look ahead
# instead with ?= syntax
for item in re.finditer("(?P<title>[\w ]+)(?=\[edit\])",wiki):
    # What this regex says is match two groups, the first will be named and called title, will have any amount
    # of whitespace or regular word characters, the second will be the characters [edit] but we don't actually
    # want this edit put in our output match objects
    print(item)


<re.Match object; span=(0, 8), match='Overview'>
<re.Match object; span=(2715, 2739), match='Access to public records'>
<re.Match object; span=(3692, 3715), match='Student medical records'>


In [2]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [98]:
import numpy as np
np.random.rand(4)

array([0.44970588, 0.99913493, 0.2886834 , 0.04610007])

In [96]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [97]:
np.array([[1, 2, 3, 4]])

array([[1, 2, 3, 4]])

In [3]:
s = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'
re.findall("(?<=[https]:\/\/)([a-zA-Z0-9.]*)",s)

['google.com', 'www.baidu.com']